# Generated by Django 5.2 on 2025-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinic_images/')),
            ],
        ),
    ]
