# Generated by Django 5.2 on 2025-04-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matab_app', '0002_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='imaging_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laboratory_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(),
        ),
    ]
