# Generated by Django 5.2 on 2025-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matab_app', '0007_patientprofile_medicalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='national_id_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
